#!/bin/bash

echo "==== Setup Wi-Fi Credentials ===="

echo "country=JP" > /etc/wpa_supplicant/wpa_supplicant.conf
echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "update_config=1" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "ap_scan=1" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo >> /etc/wpa_supplicant/wpa_supplicant.conf

cat $HOME/bin/wifi_credentials.conf >> /etc/wpa_supplicant/wpa_supplicant.conf

if [ $? != 0 ]
then
	echo "==== Setup Failed ===="
	read -p "Enter to exit" key_board
	exit 1
fi

echo "==== Done ===="
read -p "Enter to exit" key_board
exit 0