#!/bin/bash

echo "==== Download app ===="
# read app url
input=/usr/share/raspbian-http-devops/app_url.conf
while IFS= read -r app_url
do
  echo "App URL: $app_url"
done < "$input"

if [ -z ${app_url} ]
then
  echo "App is not found"
  read -p "Enter to exit" key_board
  exit 1
else
  echo "App Link: '$app_url'"
fi

# download app file
curl "$app_url" -o $HOME/aromacontroller.war 

# move app file into the server folder
file="$HOME/aromacontroller.war"

if [ -f "$file" ]
then
  mv $HOME/aromacontroller.war /opt/jetty/web/bbq/webapps
  chown jetty:jetty /opt/jetty/web/bbq/webapps/aromacontroller.war
else
  echo
  echo "==== Download app failed ===="
  read -p "Enter to exit" key_board
  exit 1
fi

# restart Jetty
echo "==== Restart server ===="
service jetty restart

if [ $? != 0 ]
then
  echo "==== Failed to restart server ===="
  read -p "Enter to exit" key_board
  exit 1
fi

echo
echo "==== Done ===="
read -p "Enter to exit" key_board
exit 0